# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ServerBaseStation_pb2 as ServerBaseStation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ServerBaseStation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DroneWebRtcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/DroneWebRtc/Connect',
                request_serializer=ServerBaseStation__pb2.ConnectRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Poll = channel.unary_unary(
                '/DroneWebRtc/Poll',
                request_serializer=ServerBaseStation__pb2.PollRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.PollResponse.FromString,
                _registered_method=True)
        self.Stream = channel.unary_unary(
                '/DroneWebRtc/Stream',
                request_serializer=ServerBaseStation__pb2.StreamOffer.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.StreamAnswer.FromString,
                _registered_method=True)


class DroneWebRtcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Poll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DroneWebRtcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=ServerBaseStation__pb2.ConnectRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.ConnectResponse.SerializeToString,
            ),
            'Poll': grpc.unary_unary_rpc_method_handler(
                    servicer.Poll,
                    request_deserializer=ServerBaseStation__pb2.PollRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.PollResponse.SerializeToString,
            ),
            'Stream': grpc.unary_unary_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=ServerBaseStation__pb2.StreamOffer.FromString,
                    response_serializer=ServerBaseStation__pb2.StreamAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DroneWebRtc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DroneWebRtc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DroneWebRtc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DroneWebRtc/Connect',
            ServerBaseStation__pb2.ConnectRequest.SerializeToString,
            ServerBaseStation__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DroneWebRtc/Poll',
            ServerBaseStation__pb2.PollRequest.SerializeToString,
            ServerBaseStation__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DroneWebRtc/Stream',
            ServerBaseStation__pb2.StreamOffer.SerializeToString,
            ServerBaseStation__pb2.StreamAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CloudStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/Cloud/Connect',
                request_serializer=ServerBaseStation__pb2.ConnectToCloudRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.ConnectToCloudResponse.FromString,
                _registered_method=True)


class CloudServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=ServerBaseStation__pb2.ConnectToCloudRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.ConnectToCloudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Cloud', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Cloud', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cloud(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Cloud/Connect',
            ServerBaseStation__pb2.ConnectToCloudRequest.SerializeToString,
            ServerBaseStation__pb2.ConnectToCloudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WebRtcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/WebRtc/Connect',
                request_serializer=ServerBaseStation__pb2.ConnectRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/WebRtc/Register',
                request_serializer=ServerBaseStation__pb2.RegisterProducerRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.RegisterProducerResponse.FromString,
                _registered_method=True)
        self.Stream = channel.unary_unary(
                '/WebRtc/Stream',
                request_serializer=ServerBaseStation__pb2.StreamOffer.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.StreamAnswer.FromString,
                _registered_method=True)
        self.IceCandidate = channel.unary_unary(
                '/WebRtc/IceCandidate',
                request_serializer=ServerBaseStation__pb2.IceCandidateRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.IceCandidateResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/WebRtc/Disconnect',
                request_serializer=ServerBaseStation__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=ServerBaseStation__pb2.DisconnectResponse.FromString,
                _registered_method=True)


class WebRtcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IceCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebRtcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=ServerBaseStation__pb2.ConnectRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.ConnectResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=ServerBaseStation__pb2.RegisterProducerRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.RegisterProducerResponse.SerializeToString,
            ),
            'Stream': grpc.unary_unary_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=ServerBaseStation__pb2.StreamOffer.FromString,
                    response_serializer=ServerBaseStation__pb2.StreamAnswer.SerializeToString,
            ),
            'IceCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.IceCandidate,
                    request_deserializer=ServerBaseStation__pb2.IceCandidateRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.IceCandidateResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=ServerBaseStation__pb2.DisconnectRequest.FromString,
                    response_serializer=ServerBaseStation__pb2.DisconnectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WebRtc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('WebRtc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebRtc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebRtc/Connect',
            ServerBaseStation__pb2.ConnectRequest.SerializeToString,
            ServerBaseStation__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebRtc/Register',
            ServerBaseStation__pb2.RegisterProducerRequest.SerializeToString,
            ServerBaseStation__pb2.RegisterProducerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebRtc/Stream',
            ServerBaseStation__pb2.StreamOffer.SerializeToString,
            ServerBaseStation__pb2.StreamAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IceCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebRtc/IceCandidate',
            ServerBaseStation__pb2.IceCandidateRequest.SerializeToString,
            ServerBaseStation__pb2.IceCandidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebRtc/Disconnect',
            ServerBaseStation__pb2.DisconnectRequest.SerializeToString,
            ServerBaseStation__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
