cc_library(
    name = "database",
    srcs = [
        "DatabaseManager.h",
    ],
    # hdrs = [],
    deps = [
    ],
    visibility = ["//visibility:public"],
    alwayslink = True,
    linkopts = ["-lpq"],
)