@startuml Component Diagram BaseStation

' left to right direction
' skinparam Monochrome true

actor BasestationAdmin as "Basestation Admin"

node BaseStation {

port WebRtc
port Grpc
port Frontend

component WebServer {

}

database Database {

}

component core {

}


' core -right- WebRtcIn

Database -right- WebServer

core -- Database

Frontend --down- WebServer

core -- WebRtc
core -- Grpc


}
BasestationAdmin -- Frontend


@enduml