cc_library(
    name = "managers",
    srcs = [
        "DeviceManager.h",
        "CameraManager.h",
        "DroneManager.h",
    ],
    # hdrs = [],
    deps = [
        "//devices"
    ],
    visibility = ["//visibility:public"],
    
)